language: python
# most of this from https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install codecov mypy types-Jinja2
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest --cov=dataspec
  - mypy --show-error-codes dataspec/
after_success:
  - codecov # submit coverage
