version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt
      - run:
          name: Run tests
          command: pytest --cov=datacraft
      - run:
          name: MyPy checks
          command: mypy --show-error-codes datacraft/
      - run:
          name: Code Coverage Upload
          command: codecov

workflows:
  sample:
    jobs:
      - build-and-test
